on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set Env
      run: echo "PROJECT_VERSION=$(cat ./toolkit/VERSION)" >> $GITHUB_ENV
    - name: Print Github Env
      run: cat $GITHUB_ENV
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=hammond95
          -Dsonar.projectKey=Hammond95_aws-data-toolkit
          -Dsonar.projectName=aws-data-toolkit
          -Dsonar.projectVersion=$PROJECT_VERSION
          -Dsonar.sources=toolkit/
          -Dsonar.language=py
          -Dsonar.python.pylint=/usr/local/bin/pylint
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.test.exclusions=tests/**
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}